### ISSUE TITLE
Split-out part of makecircle code into function that takes lon and lat and outputs a matrix

### ISSUE THREAD

**Issue by Robinlovelace** [zonebuilders/zonebuilder-rust#3]
Partly as a learning experience.

**Comment by Robinlovelace** [comment]
Looking at the matrix class here, worth adding as another dependency @dabreegster ? https://github.com/dimforge/nalgebra

**Comment by Robinlovelace** [comment]
For now just looking at a vector of vectors:

```
Vec<Vec<T>>
```

Source: https://stackoverflow.com/questions/33749114/creating-a-struct-with-an-array-matrices

**Comment by dabreegster** [comment]
It could be an excuse to play around with `nalgebra`, sure. But I would advise against using any matrix-like at all in Rust. You can shoehorn many types of data into a matrix, but it doesn't buy you anything until you're trying to do machine learning or something. To take full advantage of Rust, I'd encourage using the type system and all of the geo types represented in it. When in Rome...

I'll open up a few issues describing some next steps, if you want a bit of direction

**Comment by Robinlovelace** [comment]
> if you want a bit of direction

Yes please!

Great to try many things, can learn something from each one, you learn fastest when you fall!
