### ISSUE TITLE
Submit to crates.io

### ISSUE THREAD

**Issue by Robinlovelace** [zonebuilders/zonebuilder-rust#32]
I'm not sure what would be needed before submitting to https://crates.io/  but thought it worth opening an issue to flag this intention.

**Comment by dabreegster** [comment]
The process itself isn't too hard, you log in there and add a few things to `Cargo.toml` and follow https://doc.rust-lang.org/cargo/reference/publishing.html. But I'd vote not doing this until the library is mostly finished, to avoid lots of API version churn. After releasing it, if you make certain types of changes, there are conventions for how you update the version in the crate: https://semver.org/

**Comment by Robinlovelace** [comment]
> I'm not sure what would be needed before submitting to https://crates.io/ but thought it worth opening an issue to flag this intention.

Agreed, it's not ready yet but good to plan ahead, when the API and features are stable this will be ready to go!

Re. SemVer that is one of the things that attracts me to Rust and which means the package interdependency/toolchain system is v. reliable, more so than the likes of Python and R. In the R world many people people follow SemVer versioning but it's not as embedded as it is in Rust.

One question: are there any auto checks on crates.io to ensure you don't push changes to a crate without a major breaking change release that crash other people's code?

The CRAN system is good at that, testing packages constantly and downstream dependencies: https://cran.r-project.org/web/checks/

There is a high bar to entry onto CRAN and they remove packages that are not maintained which means the stuff on there is well tested.

**Comment by dabreegster** [comment]
> are there any auto checks on crates.io to ensure you don't push changes to a crate without a major breaking change release that crash other people's code?

Not to my knowledge. There's a tool to look for other crates that depend on yours: https://crates.io/crates/image/reverse_dependencies
You could also use https://github.com/search to find those, and manually test them.

https://github.com/rust-lang/crater exists for automated testing, but this is for testing the Rust compiler itself.

**Comment by Robinlovelace** [comment]
Shall I give this a bash or you want to do the honours @dabreegster ? As far as I can tell it's ready to ship :rocket:

**Comment by dabreegster** [comment]
All yours! https://doc.rust-lang.org/cargo/reference/publishing.html  Post here if there's issues.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/128545861-370f9d2f-862f-41d7-a654-a9c5a86e3502.png)
