### ISSUE TITLE
Add search bar to web app

### ISSUE THREAD

**Issue by Robinlovelace** [zonebuilders/zonebuilder-rust#42]
Split out from #40 

- [x] Make the app responsive; take out the "generate" button and just do everything automatically
- [x] Make the circles slider work -- I think hardcoding the distances doesn't work with `num_circles` right now.
- [x] Add a button to just download the GeoJSON produced
- [ ] Add a search box to warp somewhere else easily
- [x] Improve the form controls (show the exact number next to the sliders)
- [x] Deploy this somewhere like Github pages!

**Comment by dabreegster** [comment]
https://zonebuilders.github.io/zonebuilder-rust/ is now live! It deploys whatever's on the `main` branch, so in-flight PRs don't clobber the live site.

**Comment by Robinlovelace** [comment]
Visualisation of the current version for paper (we can update this placeholder):

![image](https://user-images.githubusercontent.com/1825120/126983234-1c047a1e-0165-4ffd-a5cb-03a361b71d72.png)

**Comment by Robinlovelace** [comment]
This is so cool. Typing in 'Hereford UK' took me instantly to the city where I was born: 

![image](https://user-images.githubusercontent.com/1825120/127978978-15211f7f-c429-432d-8724-597f0bbe54f2.png)

**Comment by Robinlovelace** [comment]
I was born in Zone F10 of the Hereford ClockBoard system. Not sure it will catch on but handy way of referring to a place with reference to a central place, which clearly exists in this case.
