### ISSUE TITLE
Offset zones so that the first segment 'points' due north

### ISSUE THREAD

**Issue by Robinlovelace** [zonebuilders/zonebuilder-rust#45]
Output from the rust version:

![image](https://user-images.githubusercontent.com/1825120/127281020-0457fb98-b8b8-4c48-a82d-cbe99a6261ba.png)

Output from the R version:

![image](https://user-images.githubusercontent.com/1825120/127281059-ae93e146-9516-4b36-9e2b-13ec754cc0d2.png)

Reasoning: 

> Another advantage of using 12 segments is that the angular distance between segments are well understood. The ‘clock position’ system describes bearings with reference to the face of a clock, relative to the direction of travel or, as is the case with the ClockBoard zoning system, relative to true North. Under this system, well established in navigation, “12 O’clock” means true North and 3, 6 and 9 O’clock mean East, South and West respectively (Hart and Battiste 1991). Following this convention, the ClockBoard zoning system aligns segment 12 with true North, enabling users to approximate their location in a city with reference to clock position .

Source: https://zonebuilders.github.io/zonebuilder/articles/paper.html#number-of-segments

**Comment by Robinlovelace** [comment]
Heads-up I've tried fixing this by changing this:

https://github.com/zonebuilders/zonebuilder-rust/blob/179a6ad3f82fb37bcb3f4bec3efac9e4ab8ba006/src/lib.rs#L209

I tried adding `+1` to that but it didn't seem to work. Any ideas @dabreegster ? I think it used to work...

**Comment by dabreegster** [comment]
![screencast](https://user-images.githubusercontent.com/1664407/127406089-d37d04c0-b035-493e-91f2-86101edf068d.gif)
For the life of me I can't get leaflet to draw the labels without having to hover, but I think the zone names and offset now work correctly

**Comment by Robinlovelace** [comment]
:tada: I think it's actually better that they show only when hovering, neater. Fantastic fix, impressed and inspired by this.
