### ISSUE TITLE
Add the label as a GeoJSON property to each zone

### ISSUE THREAD

**Issue by dabreegster** [zonebuilders/zonebuilder-rust#46]
and make sure it shows up in the Leaflet app

**Comment by dabreegster** [comment]
If you're fine with the label only showing up on hover, this is done. Some stuff in Leaflet is super easy, but...

**Comment by Robinlovelace** [comment]
Just checking the GeoJSON output.

**Comment by Robinlovelace** [comment]
Job done :tada: 

![image](https://user-images.githubusercontent.com/1825120/127408226-88c9e887-badf-4cc3-bd64-590801c6a985.png)

**Comment by Robinlovelace** [comment]
CRS works also.

![image](https://user-images.githubusercontent.com/1825120/127408468-0a8041cc-5daf-4159-99fc-4927e77ce0bc.png)
