### ISSUE TITLE
Web app memory leak

### ISSUE THREAD

**Issue by dabreegster** [zonebuilders/zonebuilder-rust#48]
Robin reported that the browser tab slows down quickly after dragging the marker around. Confirmed with Firefox's `about:performance` page. https://github.com/zonebuilders/zonebuilder-rust/blob/036add634ff48b938928d97343a230609c6d6859/web/index.html#L88 seems to be leaking the old layer. I've tried variations here from https://github.com/Leaflet/Leaflet/issues/1416, https://gis.stackexchange.com/questions/221354/removing-layer-and-redrawing-it-again-in-leaflet, and a few other places, but nothing works yet. The docs (https://leafletjs.com/reference-1.7.1.html) also don't explain anything about memory management of layers; it's unclear who owns a layer after doing `addTo(map)`.

I miss Rust already. :(

**Comment by dabreegster** [comment]
More things to try later: https://stackoverflow.com/questions/65645639/leaflet-js-memory-leak-accessing-geojson-rest-api, https://github.com/Leaflet/Leaflet/issues/5774

**Comment by Robinlovelace** [comment]
Thanks for diagnosing this and confirming the issue. If only there were a Rust crate that could do the interactive web mapping thing and not rely on JS...

**Comment by dabreegster** [comment]
There's probably some workaround for Leaflet; I just haven't found it, and because of my unfamiliarity with JS/the browser, I'm lacking the experience to easily dive into this. I'm confident it's solveable.

> If only there were a Rust crate that could do the interactive web mapping thing and not rely on JS

The point of the web app is to use standard libraries like Leaflet, not reinvent something new! What's awesome is how easy it's been to glue the two approaches together.

**Comment by dabreegster** [comment]
https://github.com/zonebuilders/zonebuilder-rust/blob/036add634ff48b938928d97343a230609c6d6859/web/index.html#L72
I think the problem is here -- we're cleaning up the main geojson layer, but not all of the markers we create for tooltips for each zone label! I'm still wrapping my head around the Leaflet memory model. When you add something to the map, I'm unclear who's supposed to own and clean it up. I think layer groups (https://leafletjs.com/examples/layers-control/) are meant to manage this. Will experiment.

**Comment by dabreegster** [comment]
Very dumb error on my part -- those markers were my attempt to draw permanent labels in the zones, instead of just tooltips. I never figured out the permanent labels, but I didn't clean up the experimental code. It was creating markers and never cleaning them up.

The leak is now fixed, but now it reveals that the new search bar doesn't quite work. I'll get that fixed, or reopen the issue to keep tracking it.

**Comment by Robinlovelace** [comment]
Thanks Dustin!
