### ISSUE TITLE
Create minimal CLI

### ISSUE THREAD

**Issue by Robinlovelace** [zonebuilders/zonebuilder-rust#5]
From https://github.com/zonebuilders/zonebuilder-rust/pull/2#issuecomment-803461717

**Comment by Robinlovelace** [comment]
Closed in #8. However, it is a bit *too* minimal - cannot pass params + needs more examples so will leave open.

**Comment by Robinlovelace** [comment]
Heads-up @dabreegster I'm taking a read of this for inspiration: https://rust-cli.github.io/book/index.html

Aiming to be able to pass args from the command line to Rust. First guess:

```
cargo run --num_vertices 4
```

To create a square - right?

**Comment by Robinlovelace** [comment]
Looks like the `clap` crate is the way to go: https://rust-lang-nursery.github.io/rust-cookbook/cli/arguments.html

**Comment by Robinlovelace** [comment]
Looking through the issues I suggest this is a good next step to go for, now we essentially have a MVP. We can duplicate the geometries produced by the `zonebuilder` R package with its default settings. Logical step: allow the user to specify different parameters from the command line to create a handy CLI tool.

**Comment by Robinlovelace** [comment]
Any guidance on next steps v. welcome @dabreegster especially as there are a few options. Default plan is to use this: https://crates.io/crates/structopt

**Comment by dabreegster** [comment]
`structopt` is great, much higher-level API than `clap`. Go for it! Let me know if you hit problems.

**Comment by Robinlovelace** [comment]
OK giving it a bash on the `cli` branch, will track progress here. I think `zb` is a reasonable name, seems there are no name clashes: https://www.google.com/search?channel=fs&client=ubuntu&q=zb+linux
