### ISSUE TITLE
Python package

### ISSUE THREAD

**Issue by pkopparla** [zonebuilders/zonebuilder-rust#55]
Hello,
This is a copy of [this](https://github.com/zonebuilders/zonebuilder/issues/43) issue from the zonebuilder R repo.
I'd like to attempt this by writing bindings to the Rust crate. Would the idea be to create bindings using the `PyO3` crate and publish as a `pip` accessible python library using `PyO3/maturin`? Should I target a certain version of Python, say 3.6+?

**Comment by dabreegster** [comment]
Hi! This would be a very welcome contribution. Your plan sounds fine to me -- I've never used `pyO3` or `maturin`, but it looks like they're the most widely used right now. I don't have an opinion on what version to target -- I'd be fine only supporting latest Python if that's easiest, but if it's not hard to handle older versions, even better. Keep us posted if you hit any snags!

**Comment by Robinlovelace** [comment]
Big :+1: from me. Possible step: I can create a `zonebuilder-python` repo, or other name, add you @pkopparla ?

**Comment by Robinlovelace** [comment]
Or we could host the Python bindings in this repo. My guess is it's better to keep them separate.

**Comment by pkopparla** [comment]
Thank you @dabreegster and @Robinlovelace , I've never used this stuff too but it looks doable.
And yes please, a blank python repo that I can make pull requests to would make it easier for the review process.

**Comment by Robinlovelace** [comment]
New repo here and you've got push access @pkopparla https://github.com/zonebuilders/zonebuilder-py/invitations
