### ISSUE TITLE
Supply default parameters

### ISSUE THREAD

**Issue by dabreegster** [zonebuilders/zonebuilder-rust#6]
The only required param to `clockboard` is the `center` point. The rest of the params have reasonable defaults. Rust has a few different patterns for representing optional params; [this blog](https://vidify.org/blog/rust-parameters/) has a good overview, though some of it probably is hard to understand at this point.

I'll give you a hint and say that in this case, probably the nicest thing to do is create a new `ClockboardOptions` struct with fields for the radii, number of segments, and boundary. We should wind up with `fn clockboard(center: Point<f64>, opts: ClockboardOptions)`. You can use the `Default` trait to supply default values and have a syntax for overriding things. https://doc.rust-lang.org/std/default/trait.Default.html has a pretty good tutorial; let me know if you get stuck

**Comment by Robinlovelace** [comment]
> I'll give you a hint and say that in this case, probably the nicest thing to do is create a new `ClockboardOptions` struct with fields for the radii, number of segments, and boundary. We should wind up with `fn clockboard(center: Point<f64>, opts: ClockboardOptions)`.

Sounds good.



> let me know if you get stuck

Suspect I will but can give it a bash!

**Comment by Robinlovelace** [comment]
Working on this one...
