### ISSUE TITLE
Generate polygons for clockboard

### ISSUE THREAD

**Issue by dabreegster** [zonebuilders/zonebuilder-rust#9]
![README-unnamed-chunk-4-1](https://user-images.githubusercontent.com/1664407/111885680-94342380-8986-11eb-87ea-f04de4b104bf.png)

I can think of two approaches to do this.

# Directly

We have the math for generating the points along a circle. What if we instead could generate the points along an arc? We specify a radius, and the start and end angle. If we look at E02 in the image above, we could generate that shape by making two arcs, with the same start/end angles and two different radii. Then we can glue the points together.

# Using boolean ops

https://github.com/21re/rust-geo-booleanop lets you take intersection/difference between polygons. There's also a way to express the clockboard pieces doing that. The caveat is that the boolean ops are harder to work with; even if you know a particular operation should yield a single non-empty polygon, you have to dig the result out of a multipolygon and make sure things turned out as you expected.

For that reason, I'd vote for the first method -- less dependencies, and the math is pretty straightforward.

**Comment by Robinlovelace** [comment]
> For that reason, I'd vote for the first method -- less dependencies, and the math is pretty straightforward.

:+1: could be faster. Simpler is definitely better.

FYI the R implementation of zonebuilder is really slow. Not an issue given the use case but it's good to be computationally efficient. From a learning perspective doing things from 1st principles is good also.

I guess the boolean geo ops will come into their own when clipping the boundary, right?

**Comment by dabreegster** [comment]
> FYI the R implementation of zonebuilder is really slow

I'm super curious why! There's nothing expensive about this algorithm at all; it needs to do a bit of math and generate a very small number of polygons. If you can make it take more than 0.0001s I'd be quite surprised.

> I guess the boolean geo ops will come into their own when clipping the boundary, right?

Correct. After this issue is done, if the boundary isn't `None`, we can clip the outermost doughnut

**Comment by Robinlovelace** [comment]
> I'm super curious why!

Not 100% sure but having seen some of the things that you and the GeoRust guys are looking at it could be GEOS. FYI it takes more than a second to create those zones on a beefy computer ; (

Reproducible example - give it a try if you get a chance @dabreegster :  

``` r
# install.packages("zonebuilder")
library(zonebuilder)
system.time({
grid = zb_quadrat(x = london_a(), ncol = 5, nrow = 5)
})
#>    user  system elapsed 
#>   0.064   0.004   0.068
plot(grid)
```

![](https://i.imgur.com/x1ue6nQ.png)

``` r
system.time({
zones = zb_zone(x = london_c(), area = london_a())
})
#>    user  system elapsed 
#>   1.009   0.011   1.032
plot(zones)
#> Error in plot.sf(x[, cname], main = cname, pal = pal, nbreaks = nbreaks, : plotting list-columns not supported
```

![](https://i.imgur.com/NFxAxpJ.png)

<sup>Created on 2021-03-20 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by Robinlovelace** [comment]
Follow-on comment: this is actually a good way of developing an idea I think. Donald Knuth I believe said something along the lines of 'get it working then optimise', not the other way around.

**Comment by dabreegster** [comment]
The second bit is about 0.81s user time -- indeed surprisingly sluggish. Maybe clipping to the boundary is a bit slow -- squinting at the boundary, it looks pretty detailed.

Anyway yeah, let's get something working first, then optimize later. In any case, I think directly writing the math to create an arc and glue it together to make the polygons is both going to be fast and simple.

**Comment by Robinlovelace** [comment]
> Anyway yeah, let's get something working first, then optimize later. In any case, I think directly writing the math to create an arc and glue it together to make the polygons is both going to be fast and simple.

Agree and think we've implemented that already, looking good!

To progress on this I think we would need to enable this line and make associated changes. Could the argument be a geojson file and/or a `Polygon` object?

https://github.com/zonebuilders/zonebuilder-rust/blob/d4181090427f5e750528697bb244e14f8ac46bf6/src/lib.rs#L79

**Comment by dabreegster** [comment]
> Could the argument be a geojson file and/or a Polygon object?

It should probably be a `Polygon`. You can do the file loading outside of that function.
